Repository COS301-SE-2022/Grid-Watch, pull requests merged in 2022-09, with the labels that each got.

#275 👷 (CI): Added code coverage functionality
  jest.preset.ts
  libs/api/ai/ticket/service/src/lib/ai/tree.spec.ts
  libs/api/ai/ticket/service/src/lib/ai/tree.ts
  merge-reports.ts
Labels: priority:high, scope:cicd, status:needs-tests, type:change, type:test

#274 💄 (UI): Added heatmap to admin application
  libs/admin-app/dashboard/src/lib/dashboard-body/dashboard-body.component.spec.ts
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.html
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.scss
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.spec.ts
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.ts
  libs/admin-app/ticket/src/lib/admin-view-body/admin-view-body.component.ts
Labels: scope:design, status:ready, type:cosmetic, priority:high-med

#288 🐛(UI) : general bug fixes and additional features
  angular.json
  apps/admin/src/app/app.module.ts
  libs/admin-app/dashboard/src/lib/admin-app-dashboard.module.ts
  libs/admin-app/dashboard/src/lib/dashboard-body/dashboard-body.component.html
  libs/admin-app/profile/src/lib/account-information/account-information.component.ts
  libs/admin-app/profile/src/lib/login-page/login-page.component.ts
  libs/admin-app/profile/src/lib/register-page/register-page.component.ts
  libs/admin-app/tech-team/.eslintrc.json
  libs/admin-app/tech-team/README.md
  libs/admin-app/tech-team/jest.config.ts
  libs/admin-app/tech-team/project.json
  libs/admin-app/tech-team/src/index.ts
  libs/admin-app/tech-team/src/lib/admin-app-tech-team.module.ts
  libs/admin-app/tech-team/src/lib/tech-team-page/tech-team-page.component.html
  libs/admin-app/tech-team/src/lib/tech-team-page/tech-team-page.component.scss
  libs/admin-app/tech-team/src/lib/tech-team-page/tech-team-page.component.spec.ts
  libs/admin-app/tech-team/src/lib/tech-team-page/tech-team-page.component.ts
  libs/admin-app/tech-team/src/test-setup.ts
  libs/admin-app/tech-team/tsconfig.json
  libs/admin-app/tech-team/tsconfig.lib.json
  libs/admin-app/tech-team/tsconfig.spec.json
  libs/admin-app/ticket/src/lib/admin-view-body/admin-view-body.component.scss
  libs/admin-app/ticket/src/lib/view-ticket-details/view-ticket-details.component.ts
  libs/api/ai/ticket/service/src/lib/api-ai-ticket-service.module.ts
  libs/api/profiles/admin/api/src/lib/api-profiles-admin-api-controller.controller.ts
  libs/api/profiles/admin/api/src/lib/api-profiles-admin-api.module.ts
  libs/api/profiles/public/api/src/lib/api-profiles-public-api.module.ts
  libs/api/profiles/public/api/src/lib/controllers/api-profiles-public-api-controller.controller.ts
  libs/api/profiles/public/repository/src/lib/api-profiles-public-repository-data-access.ts
  libs/api/profiles/tech-team/api/src/lib/api-profiles-tech-team-api.module.ts
  libs/public/home-page/src/lib/home-page-body/home-page-body.component.ts
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.ts
  libs/public/ticket/src/lib/edit-ticket/edit-ticket.component.ts
  libs/public/ticket/src/lib/ticket-body-list/ticket-body-list.component.html
  libs/public/ticket/src/lib/ticket-body-list/ticket-body-list.component.scss
  libs/public/ticket/src/lib/ticket-body-list/ticket-body-list.component.ts
  libs/public/ticket/src/lib/ticket-body-map/ticket-body-map.component.ts
  libs/public/ticket/src/lib/view-ticket/view-ticket.component.html
  libs/public/ticket/src/lib/view-ticket/view-ticket.component.scss
  libs/public/ticket/src/lib/view-ticket/view-ticket.component.ts
  libs/public/user-profile/src/lib/login-page/login-page.component.ts
  libs/public/user-profile/src/lib/my-tickets-block/my-tickets-block.component.ts
  libs/public/user-profile/src/lib/my-tickets-list/my-tickets-list.component.ts
  libs/shared-ui/src/lib/nav-bar/nav-bar.component.html
  libs/shared-ui/src/lib/nav-bar/nav-bar.component.ts
  libs/shared-ui/src/lib/services/Ticket/ticket.service.ts
  libs/shared-ui/src/lib/services/public-profile/public-profile.service.ts
  libs/shared-ui/src/lib/services/tech-team-profile/tech-team-profile.service.ts
  libs/shared-ui/src/lib/shared-ui.module.ts
  libs/tech-team/profile/src/lib/tech-team-profile/tech-team-profile.component.ts
  libs/tech-team/ticket/src/lib/ticket-view-map/ticket-view-map.component.ts
  tsconfig.base.json
Labels: scope:design, scope:ui, status:ready, type:bug, priority:high-med

#291 💄 (UI): Added toasts to the public app
  apps/admin/src/app/app.component.html
  apps/admin/src/app/app.component.scss
  apps/admin/src/app/app.module.ts
  apps/admin/src/polyfills.ts
  apps/public/src/app/app.component.html
  apps/public/src/app/app.component.scss
  apps/public/src/app/app.module.ts
  apps/public/src/polyfills.ts
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.ts
  libs/admin-app/profile/src/lib/account-information/account-information.component.spec.ts
  libs/admin-app/profile/src/lib/account-information/account-information.component.ts
  libs/admin-app/profile/src/lib/admin-app-profile.module.ts
  libs/admin-app/profile/src/lib/login-page/login-page.component.spec.ts
  libs/admin-app/profile/src/lib/login-page/login-page.component.ts
  libs/admin-app/profile/src/lib/register-page/register-page.component.spec.ts
  libs/admin-app/profile/src/lib/register-page/register-page.component.ts
  libs/admin-app/ticket/src/lib/admin-app-ticket.module.ts
  libs/admin-app/ticket/src/lib/view-ticket-details/view-ticket-details.component.spec.ts
  libs/admin-app/ticket/src/lib/view-ticket-details/view-ticket-details.component.ts
  libs/api/ai/ticket/service/src/lib/api-ai-ticket-service.module.ts
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.spec.ts
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.ts
  libs/public/ticket/src/lib/public-ticket.module.ts
  libs/shared-ui/src/index.ts
  libs/shared-ui/src/lib/services/Toast/toast.service.spec.ts
  libs/shared-ui/src/lib/services/Toast/toast.service.ts
  libs/shared-ui/src/lib/shared-ui.module.ts
  libs/shared-ui/src/lib/toast/toast.component.html
  libs/shared-ui/src/lib/toast/toast.component.scss
  libs/shared-ui/src/lib/toast/toast.component.spec.ts
  libs/shared-ui/src/lib/toast/toast.component.ts
Labels: scope:ui, status:ready, type:cosmetic, priority:med-low

#290 :lipstick: (UI): Multiple UI and aesthetic changes to multiple fields
  angular.json
  apps/admin/src/index.html
  apps/public/src/app/app.component.html
  apps/tech-team/src/app/app.component.html
  libs/admin-app/dashboard/src/lib/admin-app-dashboard.module.ts
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.html
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.scss
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.ts
  libs/api/ai/ticket/service/src/lib/api-ai-ticket-service.module.ts
  libs/public/home-page/src/lib/home-page-body/home-page-body.component.html
  libs/public/home-page/src/lib/home-page-body/home-page-body.component.scss
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.html
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.scss
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.ts
  libs/public/ticket/src/lib/public-ticket.module.ts
  libs/public/ticket/src/lib/ticket-body-list/ticket-body-list.component.html
  libs/public/ticket/src/lib/ticket-body-list/ticket-body-list.component.scss
  libs/public/ticket/src/lib/ticket-body-map/ticket-body-map.component.scss
  libs/public/ticket/src/lib/ticket-body-map/ticket-body-map.component.ts
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.html
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.scss
  libs/public/ticket/src/lib/view-ticket/view-ticket.component.html
  libs/public/ticket/src/lib/view-ticket/view-ticket.component.scss
  libs/public/ticket/src/lib/view-ticket/view-ticket.component.ts
  libs/public/user-profile/src/lib/my-profile/my-profile.component.ts
  libs/shared-assets/src/lib/shared-images/filter-icon.png
  libs/shared-assets/src/lib/shared-images/filter-icon.svg
  libs/shared-assets/src/lib/shared-images/issue-brokenlight-pin.png
  libs/shared-assets/src/lib/shared-images/issue-brokenpower-pin.png
  libs/shared-assets/src/lib/shared-images/issue-brokenrobot-pin.png
  libs/shared-assets/src/lib/shared-images/issue-maintenance-pin.png
  libs/shared-assets/src/lib/shared-images/issue-pothole-pin.png
  libs/shared-assets/src/lib/shared-images/issue-sinkhole-pin.png
  libs/shared-assets/src/lib/shared-images/issue-water-pin.png
  libs/shared-ui/src/lib/menu-options/menu-options.component.scss
  libs/tech-team/ticket/src/lib/tech-team-ticket.module.ts
  libs/tech-team/ticket/src/lib/ticket-view-page/ticket-view-page.component.html
  package.json
  yarn.lock
Labels: scope:design, scope:ui, status:on-hold, status:ready, type:cosmetic, priority:high-med

#294 :lipstick: (UI): Readded custom images
  libs/public/ticket/src/lib/ticket-body-map/ticket-body-map.component.ts
Labels: priority:medium, scope:design, scope:ui, status:ready, type:chore

#289 ✨ (ai): Add format data for AI model
  libs/api/ai/ticket/api/src/lib/api-ai-ticket-api.controller.ts
  libs/api/ai/ticket/service/src/lib/api-ai-ticket-service.service.ts
  libs/api/ai/ticket/service/src/lib/queries/api-ai-ticket-query-handler.handler.ts
Labels: priority:high, scope:api, status:ready, type:change

#287 🗃️✅(db) : Added userrating
  libs/api/ai/ticket/service/src/lib/api-ai-ticket-service.module.ts
  libs/api/profiles/public/api/src/lib/controllers/api-profiles-public-api-controller.controller.spec.ts
  libs/api/profiles/public/api/src/lib/controllers/api-profiles-public-api-controller.controller.ts
  libs/api/profiles/public/repository/src/lib/api-profiles-public-repository-data-access.spec.ts
  libs/api/profiles/public/repository/src/lib/api-profiles-public-repository-data-access.ts
  libs/api/profiles/public/service/src/lib/api-profiles-public-service.module.ts
  libs/api/profiles/public/service/src/lib/api-profiles-public.service.spec.ts
  libs/api/profiles/public/service/src/lib/api-profiles-public.service.ts
  libs/api/profiles/public/service/src/lib/commands/api-profiles-public-command-handler.handler.ts
  libs/api/profiles/public/service/src/lib/commands/api-profiles-public-command.command.ts
  prisma/admins.ts
Labels: scope:db, status:needs-info, type:enhance, priority:high-med

#299 💄 (UI):Added toasts to the tech team app
  apps/tech-team/src/app/app.component.html
  apps/tech-team/src/app/app.component.scss
  apps/tech-team/src/app/app.module.ts
  apps/tech-team/src/polyfills.ts
  libs/tech-team/profile/src/lib/login-page/login-page.component.ts
  libs/tech-team/profile/src/lib/register-tech-team/register-tech-team.component.ts
  libs/tech-team/profile/src/lib/tech-team-profile.module.ts
Labels: priority:medium, scope:ui, status:ready, type:cosmetic, priority:med-low

#300 🗃️(db): Added model to store AI data
  prisma/migrations/20220913072810_added_ai_model/migration.sql
  prisma/schema.prisma
Labels: priority:high, scope:db, status:ready, type:enhance, type:feature

#303 ✨ (ai): Created AI Dto
  angular.json
  libs/api/ai/ticket/api/shared/api-ai-ticket-api-dto/.babelrc
  libs/api/ai/ticket/api/shared/api-ai-ticket-api-dto/.eslintrc.json
  libs/api/ai/ticket/api/shared/api-ai-ticket-api-dto/README.md
  libs/api/ai/ticket/api/shared/api-ai-ticket-api-dto/jest.config.ts
  libs/api/ai/ticket/api/shared/api-ai-ticket-api-dto/package.json
  libs/api/ai/ticket/api/shared/api-ai-ticket-api-dto/project.json
  libs/api/ai/ticket/api/shared/api-ai-ticket-api-dto/src/index.ts
  libs/api/ai/ticket/api/shared/api-ai-ticket-api-dto/src/lib/api-ai-ticket-api-shared-api-ai-ticket-api-dto.spec.ts
  libs/api/ai/ticket/api/shared/api-ai-ticket-api-dto/src/lib/api-ai-ticket-api-shared-api-ai-ticket-api-dto.ts
  libs/api/ai/ticket/api/shared/api-ai-ticket-api-dto/tsconfig.json
  libs/api/ai/ticket/api/shared/api-ai-ticket-api-dto/tsconfig.lib.json
  libs/api/ai/ticket/api/shared/api-ai-ticket-api-dto/tsconfig.spec.json
  tsconfig.base.json
Labels: priority:high, scope:api, status:ready, type:change

#304 PR Fix
  libs/api/ai/ticket/api/shared/api-ai-ticket-api-dto/src/lib/api-ai-ticket-api-shared-api-ai-ticket-api-dto.ts
  libs/api/ai/ticket/repository/src/lib/api-ai-ticket-repository-data-access.ts
  libs/api/ticket/api/shared/ticketdto/src/index.ts
  prisma/migrations/20220913144218_smallfix/migration.sql
  prisma/schema.prisma
Labels: priority:high, scope:repository, status:not-ready, type:fix

#298 :lipstick: (UI): Added new home page
  apps/public/src/app/app.component.html
  libs/public/home-page/src/lib/home-page-body/home-page-body.component.html
  libs/public/home-page/src/lib/home-page-body/home-page-body.component.scss
  libs/public/ticket/src/lib/ticket-body-list/ticket-body-list.component.scss
  libs/shared-assets/src/lib/shared-images/s1.png
  libs/shared-assets/src/lib/shared-images/s2.png
  libs/shared-assets/src/lib/shared-images/s3.png
  libs/shared-assets/src/lib/shared-images/s4.png
  libs/shared-assets/src/lib/shared-images/steps1.png
  libs/shared-assets/src/lib/shared-images/steps2.png
  libs/shared-assets/src/lib/shared-images/steps3.png
  libs/shared-assets/src/lib/shared-images/steps4.png
Labels: priority:medium, scope:ui, status:ready, type:cosmetic

#305 ✨ (ai): Add training and saving AI model to database
  libs/api/ai/ticket/api/src/lib/api-ai-ticket-api.controller.ts
  libs/api/ai/ticket/repository/src/index.ts
  libs/api/ai/ticket/repository/src/lib/api-ai-ticket-repository.module.ts
  libs/api/ai/ticket/service/src/lib/api-ai-ticket-service.module.ts
  libs/api/ai/ticket/service/src/lib/api-ai-ticket-service.service.ts
  libs/api/ai/ticket/service/src/lib/commands/api-ai-ticket-command.command.ts
  libs/api/ai/ticket/service/src/lib/commands/api-ai-ticket-handler.handler.ts
  libs/api/ai/ticket/service/src/lib/queries/api-ai-ticket-query-handler.handler.ts
  libs/api/ai/ticket/service/src/lib/queries/api-ai-ticket-query.query.ts
  libs/api/ticket/service/src/lib/api-ticket-service.module.ts
Labels: priority:high, scope:api, status:ready, type:change

#306 🗃️ (db) : Added additional CRUD operations+add field
  libs/api/ai/ticket/api/shared/api-ai-ticket-api-dto/src/lib/api-ai-ticket-api-shared-api-ai-ticket-api-dto.ts
  libs/api/ai/ticket/repository/src/lib/api-ai-ticket-repository-data-access.ts
  prisma/schema.prisma
Labels: priority:medium, scope:db, status:ready, type:feature

#307 💄 (UI): CSS changes to the admin app
  libs/admin-app/ticket/src/lib/admin-view-body/admin-view-body.component.html
  libs/admin-app/ticket/src/lib/view-ticket-details/view-ticket-details.component.html
  libs/admin-app/ticket/src/lib/view-ticket-details/view-ticket-details.component.scss
  libs/admin-app/ticket/src/lib/view-ticket-details/view-ticket-details.component.ts
  libs/tech-team/ticket/src/lib/edit-accepted-ticket/edit-accepted-ticket.component.html
  libs/tech-team/ticket/src/lib/edit-accepted-ticket/edit-accepted-ticket.component.scss
  libs/tech-team/ticket/src/lib/edit-accepted-ticket/edit-accepted-ticket.component.ts
  prisma/migrations/20220915095417_new_mig/migration.sql
Labels: priority:med-low

#309 :lipstick: (UI): Admin and Public
  libs/admin-app/dashboard/src/lib/admin-app-dashboard.module.ts
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.html
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.scss
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.ts
  libs/public/ticket/src/lib/ticket-body-list/ticket-body-list.component.html
  libs/public/ticket/src/lib/ticket-body-list/ticket-body-list.component.scss
  prisma/migrations/20220916071155_added_ai_type/migration.sql
Labels: priority:medium, scope:ui, status:ready, type:cosmetic

#310 🌱(db) : Created large amounts of ticket seeds
  prisma/migrations/20220915152245_newfield/migration.sql
  prisma/tickets.ts
Labels: priority:high, scope:api, scope:db, status:ready, type:feature

#308 🎨 (ai): Add ai functionality to current estimate calculations
  libs/api/ai/ticket/api/src/lib/api-ai-ticket-api.controller.ts
  libs/api/ai/ticket/service/src/lib/ai/tree.spec.ts
  libs/api/ai/ticket/service/src/lib/ai/tree.ts
  libs/api/ai/ticket/service/src/lib/api-ai-ticket-service.module.ts
  libs/api/ai/ticket/service/src/lib/api-ai-ticket-service.service.ts
  libs/api/ai/ticket/service/src/lib/queries/api-ai-ticket-query-handler.handler.ts
  libs/api/ai/ticket/service/src/lib/queries/api-ai-ticket-query.query.ts
  prisma/migrations/20220914152303_added_ai_type/migration.sql
Labels: priority:high, scope:api, status:ready, type:change, type:enhance

#312 💄 (UI):Tech Team application profile editing
  libs/admin-app/tech-team/src/lib/admin-app-tech-team.module.ts
  libs/admin-app/tech-team/src/lib/tech-team-page/tech-team-page.component.html
  libs/admin-app/tech-team/src/lib/tech-team-page/tech-team-page.component.scss
  libs/admin-app/tech-team/src/lib/tech-team-page/tech-team-page.component.spec.ts
  libs/admin-app/tech-team/src/lib/tech-team-page/tech-team-page.component.ts
  libs/api/profiles/tech-team/api/src/lib/controllers/api-profiles-tech-team-api-controller.controller.ts
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.ts
  libs/public/ticket/src/lib/edit-ticket/edit-ticket.component.ts
  libs/public/ticket/src/lib/ticket-body-list/ticket-body-list.component.scss
  libs/shared-ui/src/lib/services/tech-team-profile/tech-team-profile.service.ts
  libs/tech-team/profile/src/index.ts
  libs/tech-team/profile/src/lib/profile-settings/profile-settings.component.html
  libs/tech-team/profile/src/lib/profile-settings/profile-settings.component.scss
  libs/tech-team/profile/src/lib/profile-settings/profile-settings.component.spec.ts
  libs/tech-team/profile/src/lib/profile-settings/profile-settings.component.ts
  libs/tech-team/profile/src/lib/register-tech-team/register-tech-team.component.html
  libs/tech-team/profile/src/lib/register-tech-team/register-tech-team.component.ts
  libs/tech-team/profile/src/lib/tech-team-profile.module.ts
  libs/tech-team/profile/src/lib/tech-team-profile/tech-team-profile.component.html
  libs/tech-team/profile/src/lib/tech-team-profile/tech-team-profile.component.ts
  libs/tech-team/ticket/src/lib/ticket-view-page/ticket-view-page.component.ts
Labels: priority:high, scope:ui, status:ready

#313 🚑🐛 (front-end) : Fixed small bug + added table to admin view
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.html
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.scss
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.ts
  libs/shared-ui/src/lib/services/tech-team-profile/tech-team-profile.service.ts
  libs/tech-team/profile/src/lib/login-page/login-page.component.ts
  prisma/migrations/20220915095417_new_mig/migration.sql
  prisma/migrations/20220915152245_newfield/migration.sql
  prisma/migrations/20220916071155_added_ai_type/migration.sql
Labels: priority:high, scope:ui, status:ready, type:bug, scope:services

#316 ✨ (ai): Added Decision trees and fixed bugs
  libs/api/ai/ticket/service/src/lib/ai/div-node.spec.ts
  libs/api/ai/ticket/service/src/lib/ai/div-node.ts
  libs/api/ai/ticket/service/src/lib/ai/tree.ts
  libs/api/ai/ticket/service/src/lib/api-ai-ticket-service.module.ts
  libs/api/ai/ticket/service/src/lib/api-ai-ticket-service.service.ts
  libs/api/ai/ticket/service/src/lib/decision_tree/best-split.spec.ts
  libs/api/ai/ticket/service/src/lib/decision_tree/best-split.ts
  libs/api/ai/ticket/service/src/lib/decision_tree/decision-tree.spec.ts
  libs/api/ai/ticket/service/src/lib/decision_tree/decision-tree.ts
  libs/api/ai/ticket/service/src/lib/decision_tree/node.spec.ts
  libs/api/ai/ticket/service/src/lib/decision_tree/node.ts
  prisma/migrations/20220523091741_added_tech_team_relation/migration.sql
  prisma/migrations/20220525171642_added_ticket_image/migration.sql
  prisma/migrations/20220528120449_pictureupdated/migration.sql
  prisma/migrations/20220529151528_picture_modified/migration.sql
  prisma/migrations/20220607105026_added_tech_team_ticket/migration.sql
  prisma/migrations/20220608103326_added_ticket_image/migration.sql
  prisma/migrations/20220609082500_added_login/migration.sql
  prisma/migrations/20220609093748_assigned_tickets/migration.sql
  prisma/migrations/20220609121757_standardized_fieldnames/migration.sql
  prisma/migrations/20220625192800_techteamticketfix/migration.sql
  prisma/migrations/20220626062155_added_subtasks/migration.sql
  prisma/migrations/20220626072349_addedsubtasks/migration.sql
  prisma/migrations/20220626083341_updated_subtasks/migration.sql
  prisma/migrations/20220626083436_subtasktypofix/migration.sql
  prisma/migrations/20220707103746_fixed_typo_in_user_model/migration.sql
  prisma/migrations/20220707192401_added_password_to_admin/migration.sql
  prisma/migrations/20220707192433_added_password_to_admin/migration.sql
  prisma/migrations/20220714100316_updated_techteam_specialisations/migration.sql
  prisma/migrations/20220714165807_removed_techteamticket/migration.sql
  prisma/migrations/20220714185228_fixedbug_intickets/migration.sql
  prisma/migrations/20220717131214_/migration.sql
  prisma/migrations/20220721172719_addedlocationandusersticket/migration.sql
  prisma/migrations/20220721182733_addedstreetaddress/migration.sql
  prisma/migrations/20220722112700_optional_user_relations/migration.sql
  prisma/migrations/20220726224052_changeduseridfieldadmin/migration.sql
  prisma/migrations/20220726224750_updatedfieldstreetaddress/migration.sql
  prisma/migrations/20220727070552_addedcitiestechteam/migration.sql
  prisma/migrations/20220728095015_addedcurrentsubtask/migration.sql
  prisma/migrations/20220824122346_addeduserrating/migration.sql
  prisma/migrations/20220824172319_minordefualtvaluechange/migration.sql
  prisma/migrations/20220828135701_fixedtypo/migration.sql
  prisma/migrations/20220913072810_added_ai_model/migration.sql
  prisma/migrations/20220913134711_fixedtypo/migration.sql
  prisma/migrations/20220913134802_revertpreviouschange/migration.sql
  prisma/migrations/20220913140102_added_tickettype_and_cities_aimodel/migration.sql
  prisma/migrations/20220913144218_smallfix/migration.sql
  prisma/migrations/20220914152303_added_ai_type/migration.sql
  prisma/migrations/20220917125227_new_migration/migration.sql
Labels: priority:high, scope:api, status:ready, type:change

#322 💄(ui) : Fixed small bug
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.ts
Labels: priority:high, scope:ui, status:ready, type:fix

#321 :lipstick: (UI): Made the maps and ticket list displays uniform across applications
  apps/admin/src/app/app.component.html
  apps/admin/src/index.html
  apps/tech-team/src/app/app.component.html
  libs/admin-app/dashboard/src/lib/dashboard-body/dashboard-body.component.html
  libs/admin-app/dashboard/src/lib/dashboard-body/dashboard-body.component.scss
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.html
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.scss
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.ts
  libs/admin-app/ticket/src/lib/admin-view-body/admin-view-body.component.html
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.html
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.ts
  libs/tech-team/ticket/src/lib/edit-accepted-ticket/edit-accepted-ticket.component.html
  libs/tech-team/ticket/src/lib/ticket-view-map/ticket-view-map.component.ts
  libs/tech-team/ticket/src/lib/ticket-view-page/ticket-view-page.component.html
  libs/tech-team/ticket/src/lib/ticket-view-page/ticket-view-page.component.scss
Labels: scope:ui, status:ready, type:cosmetic, priority:med-low

#327 🐛💄(ui) : Fixed some bugs on front-end and improved some UI + biased seeds
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.html
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.ts
  libs/public/ticket/src/lib/public-ticket.module.ts
  libs/public/ticket/src/lib/ticket-body-map/ticket-body-map.component.ts
  prisma/tickets.ts
Labels: scope:ui, status:ready, type:enhance, type:fix, priority:high-med

#328 💄(UI) : Small bug fixes around the application
  apps/admin/src/styles.scss
  apps/public/Dockerfile
  apps/tech-team/src/app/app.module.ts
  apps/tech-team/src/styles.scss
  libs/admin-app/profile/src/lib/admin-profile/admin-profile.component.scss
  libs/admin-app/tech-team/src/lib/tech-team-page/tech-team-page.component.html
  libs/admin-app/tech-team/src/lib/tech-team-page/tech-team-page.component.scss
  libs/admin-app/tech-team/src/lib/tech-team-page/tech-team-page.component.spec.ts
  libs/admin-app/tech-team/src/lib/tech-team-page/tech-team-page.component.ts
  libs/admin-app/ticket/src/lib/admin-view-body/admin-view-body.component.scss
  libs/admin-app/ticket/src/lib/view-ticket-details/view-ticket-details.component.html
  libs/admin-app/ticket/src/lib/view-ticket-details/view-ticket-details.component.scss
  libs/admin-app/ticket/src/lib/view-ticket-details/view-ticket-details.component.ts
  libs/api/profiles/tech-team/api/src/lib/controllers/api-profiles-tech-team-api-controller.controller.ts
  libs/public/ticket/src/lib/public-ticket.module.ts
  libs/public/ticket/src/lib/ticket-body-list/ticket-body-list.component.ts
  libs/public/user-profile/src/lib/my-tickets-list/my-tickets-list.component.ts
  libs/shared-ui/src/lib/message-dialog/message-dialog.component.html
  libs/shared-ui/src/lib/message-dialog/message-dialog.component.ts
  libs/shared-ui/src/lib/nav-bar/nav-bar.component.html
  libs/shared-ui/src/lib/services/tech-team-profile/tech-team-profile.service.ts
  libs/tech-team/profile/src/lib/profile-settings/profile-settings.component.html
  libs/tech-team/profile/src/lib/profile-settings/profile-settings.component.scss
  libs/tech-team/profile/src/lib/tech-team-profile/tech-team-profile.component.html
  libs/tech-team/profile/src/lib/tech-team-profile/tech-team-profile.component.scss
  libs/tech-team/profile/src/lib/tech-team-profile/tech-team-profile.component.ts
  libs/tech-team/ticket/src/lib/edit-accepted-ticket/edit-accepted-ticket.component.html
  libs/tech-team/ticket/src/lib/ticket-view-details/ticket-view-details.component.html
  libs/tech-team/ticket/src/lib/ticket-view-details/ticket-view-details.component.ts
  libs/tech-team/ticket/src/lib/ticket-view-map/ticket-view-map.component.ts
  libs/tech-team/ticket/src/lib/ticket-view-page/ticket-view-page.component.html
  libs/tech-team/ticket/src/lib/ticket-view-page/ticket-view-page.component.scss
  libs/tech-team/ticket/src/lib/ticket-view-page/ticket-view-page.component.ts
Labels: priority:high, scope:ui, status:ready, type:bug

#324 💄 (UI): Added filtering to heatmap
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.html
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.scss
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.ts
Labels: scope:ui, status:ready, type:enhance, priority:high-med

#329 💄 (UI): Admin, attempted toast fix and fixed scrollbars
  apps/admin/src/app/app.component.html
  apps/public/src/app/app.component.html
  libs/admin-app/tech-team/src/lib/tech-team-page/tech-team-page.component.scss
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.ts
Labels: priority:medium

#330 🐛 (ui) : Small fix
  libs/public/home-page/src/lib/home-page-body/home-page-body.component.html
Labels: priority:high, scope:ui, status:ready, type:fix

#331 :lipstick: (UI): Fixed toasts and minor changes
  apps/admin/src/app/app.component.html
  apps/public/src/app/app.component.html
  apps/tech-team/src/app/app.component.html
  libs/public/home-page/src/lib/home-page-body/home-page-body.component.html
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.html
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.ts
  libs/public/ticket/src/lib/view-ticket/view-ticket.component.html
Labels: priority:high
