Repository COS301-SE-2022/Grid-Watch, pull requests merged in 2022-08, with the labels that each got.

#258 💄(UI):Added responsive admin graph
  apps/tech-team/src/app/app.module.ts
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.spec.ts
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.ts
Labels: priority:high-med

#252 🗃️🌱 (db) : Added currentSubtask operations and modified seeds
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.html
  libs/admin-app/dashboard/src/lib/dashboard-overview/dashboard-overview.component.ts
  libs/api/profiles/admin/api/shared/api-profiles-admin-api-dto/src/lib/admin-dto.ts
  libs/api/profiles/admin/repository/src/lib/api-profiles-admin-repository-data-access.spec.ts
  libs/api/profiles/admin/repository/src/lib/api-profiles-admin-repository-data-access.ts
  libs/api/profiles/public/api/shared/api-profiles-public-api-dto/src/lib/user-dto.ts
  libs/api/profiles/public/repository/src/lib/api-profiles-public-repository-data-access.spec.ts
  libs/api/profiles/public/repository/src/lib/api-profiles-public-repository-data-access.ts
  libs/api/profiles/tech-team/api/shared/techteamdto/src/lib/api-profiles-tech-team-api-shared-techteamdto.ts
  libs/api/profiles/tech-team/repository/src/lib/api-profiles-tech-team-repository-data-access.spec.ts
  libs/api/profiles/tech-team/repository/src/lib/api-profiles-tech-team-repository-data-access.ts
  libs/api/ticket/api/shared/ticketdto/src/lib/api-ticket-api-shared-ticketdto.ts
  libs/api/ticket/repository/src/lib/api-ticket-repository-data-access.spec.ts
  libs/api/ticket/repository/src/lib/api-ticket-repository-data-access.ts
  libs/shared-assets/src/lib/shared-images/noelecseed.jpg
  libs/shared-assets/src/lib/shared-images/nopowerseed.jpg
  libs/shared-assets/src/lib/shared-images/pipeburstroad.jpg
  libs/shared-assets/src/lib/shared-images/potholeseed.jpg
  libs/shared-assets/src/lib/shared-images/roadfloodedseed.jpeg
  libs/shared-ui/src/lib/services/Ticket/ticket.service.ts
  prisma/migrations/20220727070552_addedcitiestechteam/migration.sql
  prisma/migrations/20220728095015_addedcurrentsubtask/migration.sql
  prisma/migrations/20220824122346_addeduserrating/migration.sql
  prisma/migrations/20220824172319_minordefualtvaluechange/migration.sql
  prisma/migrations/20220828135701_fixedtypo/migration.sql
  prisma/pictures.ts
  prisma/schema.prisma
  prisma/subtasks.ts
  prisma/tickets.ts
Labels: priority:high, scope:db, status:needs-info, type:feature, type:test

#266 ✨ (AI): Added Genetic Programming model and unit testing
  libs/api/ai/ticket/service/src/lib/ai/div-node.spec.ts
  libs/api/ai/ticket/service/src/lib/ai/div-node.ts
  libs/api/ai/ticket/service/src/lib/ai/gp.spec.ts
  libs/api/ai/ticket/service/src/lib/ai/gp.ts
  libs/api/ai/ticket/service/src/lib/ai/internal-node.spec.ts
  libs/api/ai/ticket/service/src/lib/ai/internal-node.ts
  libs/api/ai/ticket/service/src/lib/ai/leaf-node.spec.ts
  libs/api/ai/ticket/service/src/lib/ai/leaf-node.ts
  libs/api/ai/ticket/service/src/lib/ai/min-node.spec.ts
  libs/api/ai/ticket/service/src/lib/ai/min-node.ts
  libs/api/ai/ticket/service/src/lib/ai/mult-node.spec.ts
  libs/api/ai/ticket/service/src/lib/ai/mult-node.ts
  libs/api/ai/ticket/service/src/lib/ai/node.spec.ts
  libs/api/ai/ticket/service/src/lib/ai/node.ts
  libs/api/ai/ticket/service/src/lib/ai/plus-node.spec.ts
  libs/api/ai/ticket/service/src/lib/ai/plus-node.ts
  libs/api/ai/ticket/service/src/lib/ai/tree.spec.ts
  libs/api/ai/ticket/service/src/lib/ai/tree.ts
  libs/api/ai/ticket/service/src/lib/api-ai-ticket-service.module.ts
  package.json
  yarn.lock
Labels: priority:high, scope:api, status:needs-info, type:feature
