Repository COS301-SE-2022/Grid-Watch, pull requests merged in 2022-05, with the labels that each got.

#11 👷 (CI/CD) : Added CI scripts
  .github/workflows/ci.yml
  angular.json
  apps/public-e2e/src/integration/app.spec.ts
  libs/public/ticket/.eslintrc.json
  libs/public/ticket/README.md
  libs/public/ticket/jest.config.ts
  libs/public/ticket/project.json
  libs/public/ticket/src/index.ts
  libs/public/ticket/src/lib/public-ticket.module.ts
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.html
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.scss
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.spec.ts
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.ts
  libs/public/ticket/src/test-setup.ts
  libs/public/ticket/tsconfig.json
  libs/public/ticket/tsconfig.lib.json
  libs/public/ticket/tsconfig.spec.json
  nx.json
  package.json
  tsconfig.base.json
  yarn.lock
Labels: priority:high, scope:cicd, status:needs-tests, type:feature

#14 ✨(api): Added working controller
  apps/api/src/app/app.module.ts
  libs/api/ticket/api/src/lib/api-ticket-api.module.ts
  libs/api/ticket/api/src/lib/ticket.controller.spec.ts
  libs/api/ticket/api/src/lib/ticket.controller.ts
Labels: priority:high, scope:api, status:ready, type:change

#16 🗃️ (datbase): added prisma dependency
  .env
  package.json
  prisma/schema.prisma
  yarn.lock
Labels: priority:medium, scope:repository, status:ready, type:chore

#21 🎨 (api): Renamed controllers to adhere to naming convention
  libs/api/ticket/api/src/lib/api-ticket-api-controller.controller.spec.ts
  libs/api/ticket/api/src/lib/api-ticket-api-controller.controller.ts
  libs/api/ticket/api/src/lib/api-ticket-api.module.ts
Labels: priority:medium, scope:api, status:ready, type:change

#28 🗃️(prisma/db) : Added prisma schema and CRUD operations
  libs/api/ticket/repository/src/lib/api-ticket-repository-data-access.spec.ts
  libs/api/ticket/repository/src/lib/api-ticket-repository-data-access.ts
  libs/api/ticket/repository/src/lib/api-ticket-repository.module.ts
  nx.json
  package.json
  prisma/schema.prisma
  yarn.lock
Labels: priority:medium, scope:db, status:ready, type:feature, type:fix

#29 ✨ (api): Added simple controller endpoints
  libs/api/ticket/api/src/lib/api-ticket-api-controller.controller.ts
Labels: priority:medium, scope:api, status:not-ready, type:change

#31 ✨ (api): Added required endpoints
  libs/api/ticket/api/src/lib/api-ticket-api-controller.controller.ts
  libs/api/ticket/api/src/lib/api-ticket-api.module.ts
  libs/api/ticket/api/src/lib/controllers/api-ticket-api-controller.controller.spec.ts
  libs/api/ticket/api/src/lib/controllers/api-ticket-api-controller.controller.ts
  libs/api/ticket/api/src/lib/dto/ticket-dto.spec.ts
  libs/api/ticket/api/src/lib/dto/ticket.dto.ts
  libs/api/ticket/api/tsconfig.spec.json
  package.json
  yarn.lock
Labels: priority:high, scope:api, status:ready, type:change

#25 💄 (UI) : Added home page component
  angular.json
  apps/public/src/app/app.component.html
  apps/public/src/app/app.module.ts
  apps/public/src/assets/under-construction.svg
  apps/public/src/assets/user-regular.svg
  libs/api/ticket/service/src/lib/api-ticket-service.module.ts
  libs/api/ticket/service/src/lib/api-ticket.service.spec.ts
  libs/api/ticket/service/src/lib/api-ticket.service.ts
  libs/public/home-page/src/lib/home-page-body/home-page-body.component.html
  libs/public/home-page/src/lib/home-page-body/home-page-body.component.scss
  libs/public/shared-ui/.eslintrc.json
  libs/public/shared-ui/README.md
  libs/public/shared-ui/jest.config.ts
  libs/public/shared-ui/project.json
  libs/public/shared-ui/src/index.ts
  libs/public/shared-ui/src/lib/nav-bar/nav-bar.component.html
  libs/public/shared-ui/src/lib/nav-bar/nav-bar.component.scss
  libs/public/shared-ui/src/lib/nav-bar/nav-bar.component.spec.ts
  libs/public/shared-ui/src/lib/nav-bar/nav-bar.component.ts
  libs/public/shared-ui/src/lib/public-shared-ui.module.ts
  libs/public/shared-ui/src/test-setup.ts
  libs/public/shared-ui/tsconfig.json
  libs/public/shared-ui/tsconfig.lib.json
  libs/public/shared-ui/tsconfig.spec.json
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.html
  tsconfig.base.json
Labels: priority:medium, scope:ui, status:needs-info, type:cosmetic

#35 ✨ Added Service layer
  libs/api/ticket/repository/src/index.ts
  libs/api/ticket/service/src/index.ts
  libs/api/ticket/service/src/lib/api-ticket-service.module.ts
  libs/api/ticket/service/src/lib/api-ticket.service.spec.ts
  libs/api/ticket/service/src/lib/api-ticket.service.ts
  libs/api/ticket/service/src/lib/commands/api-ticket-command-handler.handler.ts
  libs/api/ticket/service/src/lib/commands/api-ticket-command.command.ts
  libs/api/ticket/service/src/lib/queries/api-ticket-query.query.ts
  libs/api/ticket/service/src/lib/queries/api-ticket-quety-handler.handler.ts
  package.json
  yarn.lock
Labels: priority:high, status:needs-tests, type:enhance, scope:services

#36 ✨ Enhance the service layer
  libs/api/ticket/service/src/lib/api-ticket.service.ts
  libs/api/ticket/service/src/lib/commands/api-ticket-command-handler.handler.ts
  libs/api/ticket/service/src/lib/commands/api-ticket-command.command.ts
  libs/api/ticket/service/src/lib/queries/api-ticket-query.query.ts
  libs/api/ticket/service/src/lib/queries/api-ticket-quety-handler.handler.ts
Labels: priority:medium, status:needs-tests, type:enhance, scope:services

#37 ✅(UI) : Added Tests
  apps/public/src/assets/upload-solid.svg
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.html
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.scss
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.spec.ts
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.ts
  libs/public/ticket/src/lib/public-ticket.module.ts
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.html
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.spec.ts
Labels: priority:medium, scope:ui, status:on-hold, type:cosmetic

#40 🎨 (api): Connected controller to service layer
  libs/api/ticket/api/src/lib/api-ticket-api.module.ts
  libs/api/ticket/api/src/lib/controllers/api-ticket-api-controller.controller.spec.ts
  libs/api/ticket/api/src/lib/controllers/api-ticket-api-controller.controller.ts
Labels: priority:high, scope:api, status:ready, type:change, scope:services

#48 🐛 (api): Fix param type issue in controller
  libs/api/ticket/api/src/lib/controllers/api-ticket-api-controller.controller.ts
Labels: priority:high, scope:api, status:ready, type:fix

#53 🐛 (api): Fixes to api and service layer
  libs/api/ticket/api/src/lib/controllers/api-ticket-api-controller.controller.ts
  libs/api/ticket/service/src/lib/api-ticket-service.module.ts
Labels: priority:high, scope:api, status:ready, type:fix, scope:services

#55 🐛 (api): Fix controller get all tickets
  libs/api/ticket/api/src/lib/controllers/api-ticket-api-controller.controller.ts
Labels: priority:high, scope:api, status:ready, type:fix

#59 👽️(UI) : Added API calls
  libs/admin-app/ticket/src/lib/admin-view-body/admin-view-body.component.spec.ts
  libs/api/ticket/api/src/lib/dto/ticket.dto.ts
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.html
  libs/public/ticket/src/lib/edit-ticket/edit-ticket.component.html
  libs/public/ticket/src/lib/edit-ticket/edit-ticket.component.spec.ts
  libs/public/ticket/src/lib/edit-ticket/edit-ticket.component.ts
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.html
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.scss
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.ts
  libs/public/ticket/src/lib/ticket-settings-options/ticket-settings-options.component.html
Labels: priority:high, scope:ui, status:needs-tests, type:enhance

#61 ✅ (api): Added testing to the controllers
  libs/api/ticket/api/src/lib/controllers/api-ticket-api-controller.controller.spec.ts
Labels: priority:high, scope:api, status:ready, type:test

#60 🚸 (UI) : Enhanced user experinece
  apps/public/src/assets/image-solid.svg
  apps/public/src/assets/solid_example.png
  apps/public/src/assets/under-construction.jpg
  libs/admin-app/ticket/src/lib/admin-app-ticket.module.ts
  libs/admin-app/ticket/src/lib/admin-view-body/admin-view-body.component.html
  libs/admin-app/ticket/src/lib/admin-view-body/admin-view-body.component.ts
  libs/admin-app/ticket/src/lib/view-ticket-details/view-ticket-details.component.html
  libs/admin-app/ticket/src/lib/view-ticket-details/view-ticket-details.component.spec.ts
  libs/admin-app/ticket/src/lib/view-ticket-details/view-ticket-details.component.ts
  libs/api/ticket/api/src/index.ts
  libs/public/home-page/src/lib/home-page-body/home-page-body.component.html
  libs/public/shared-ui/src/lib/nav-bar/nav-bar.component.html
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.html
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.ts
  libs/public/ticket/src/lib/edit-ticket/edit-ticket.component.html
  libs/public/ticket/src/lib/edit-ticket/edit-ticket.component.ts
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.html
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.ts
  libs/public/ticket/src/lib/ticket-settings-options/ticket-settings-options.component.ts
  tsconfig.base.json
Labels: priority:medium, scope:ui, status:ready, type:cosmetic

#62 ✅ (service):Added tests to the services
  libs/api/ticket/service/src/lib/api-ticket.service.spec.ts
  libs/api/ticket/service/src/lib/dto/ticket-dto.spec.ts
  libs/api/ticket/service/src/lib/dto/ticket.dto.ts
Labels: priority:high, status:ready, type:test, scope:services

#64 ✅ (db/prisma):Added tests for the db
  libs/api/ticket/repository/src/lib/api-ticket-repository-data-access.spec.ts
  libs/api/ticket/repository/src/lib/dto/ticket-dto.spec.ts
  libs/api/ticket/repository/src/lib/dto/ticket-dto.ts
Labels: priority:medium, scope:db, status:ready, type:test

#106 ✨ (UI) : Created Accepted Ticket view for tech team
  libs/shared-ui/src/lib/nav-bar/nav-bar.component.ts
  libs/tech-team/ticket/src/index.ts
  libs/tech-team/ticket/src/lib/accepted-ticket-view/accepted-ticket-view.component.html
  libs/tech-team/ticket/src/lib/accepted-ticket-view/accepted-ticket-view.component.scss
  libs/tech-team/ticket/src/lib/accepted-ticket-view/accepted-ticket-view.component.spec.ts
  libs/tech-team/ticket/src/lib/accepted-ticket-view/accepted-ticket-view.component.ts
  libs/tech-team/ticket/src/lib/edit-accepted-ticket/edit-accepted-ticket.component.html
  libs/tech-team/ticket/src/lib/edit-accepted-ticket/edit-accepted-ticket.component.scss
  libs/tech-team/ticket/src/lib/edit-accepted-ticket/edit-accepted-ticket.component.spec.ts
  libs/tech-team/ticket/src/lib/edit-accepted-ticket/edit-accepted-ticket.component.ts
  libs/tech-team/ticket/src/lib/tech-team-ticket.module.ts
  libs/tech-team/ticket/src/lib/ticket-view-details/ticket-view-details.component.html
Labels: scope:ui, status:needs-tests, type:feature, priority:high-med

#109 🗃️(db) : Added new models to schema and additional CRUD operations
  libs/api/profiles/tech-team/repository/src/lib/api-profiles-tech-team-repository-data-access.spec.ts
  libs/api/profiles/tech-team/repository/src/lib/api-profiles-tech-team-repository-data-access.ts
  libs/api/ticket/repository/src/lib/api-ticket-repository-data-access.ts
  prisma/schema.prisma
Labels: scope:db, scope:repository, status:ready, type:feature, priority:high-med

#110 ✨(api): Added Controllers for Tech Team
  apps/api/src/app/app.module.ts
  libs/api/profiles/tech-team/api/src/lib/api-profiles-tech-team-api.module.ts
  libs/api/profiles/tech-team/api/src/lib/controllers/api-profiles-tech-team-api-controller.controller.spec.ts
  libs/api/profiles/tech-team/api/src/lib/controllers/api-profiles-tech-team-api-controller.controller.ts
  libs/api/profiles/tech-team/api/src/lib/dto/api-profiles-tech-team-api.dto.spec.ts
  libs/api/profiles/tech-team/api/src/lib/dto/api-profiles-tech-team-api.dto.ts
Labels: priority:high, scope:api, status:ready, type:feature

#114 🗃️ (db): Added migrations
  prisma/migrations/20220523091741_added_tech_team_relation/migration.sql
  prisma/migrations/migration_lock.toml
Labels: priority:medium, scope:db, status:ready, type:feature

#121 ✨ (UI) : Added basic sort functionality and upvote functionality
  libs/admin-app/ticket/src/lib/admin-app-ticket.module.ts
  libs/admin-app/ticket/src/lib/admin-view-body/admin-view-body.component.html
  libs/admin-app/ticket/src/lib/admin-view-body/admin-view-body.component.ts
  libs/api/ticket/api/src/lib/controllers/api-ticket-api-controller.controller.ts
  libs/api/ticket/repository/src/lib/api-ticket-repository-data-access.ts
  libs/api/ticket/service/src/lib/api-ticket-service.module.ts
  libs/api/ticket/service/src/lib/api-ticket.service.ts
  libs/api/ticket/service/src/lib/queries/api-ticket-query.query.ts
  libs/api/ticket/service/src/lib/queries/api-ticket-quety-handler.handler.ts
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.html
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.ts
  libs/tech-team/ticket/src/lib/edit-accepted-ticket/edit-accepted-ticket.component.html
  libs/tech-team/ticket/src/lib/edit-accepted-ticket/edit-accepted-ticket.component.ts
Labels: scope:ui, status:needs-tests, type:feature, priority:high-med

#124 ✨ (API) : Added Sort functionality to Admin View
  libs/admin-app/ticket/src/lib/admin-view-body/admin-view-body.component.html
  libs/admin-app/ticket/src/lib/admin-view-body/admin-view-body.component.ts
  libs/api/ticket/api/src/lib/controllers/api-ticket-api-controller.controller.ts
  libs/api/ticket/repository/src/lib/api-ticket-repository-data-access.ts
  libs/api/ticket/service/src/lib/api-ticket-service.module.ts
  libs/api/ticket/service/src/lib/api-ticket.service.ts
  libs/api/ticket/service/src/lib/queries/api-ticket-query.query.ts
  libs/api/ticket/service/src/lib/queries/api-ticket-quety-handler.handler.ts
Labels: scope:api, scope:repository, scope:ui, status:needs-tests, type:feature, scope:services, priority:high-med

#128 ✨ :(API) : Added Filter Functionality
  apps/tech-team-e2e/src/integration/app.spec.ts
  libs/admin-app/ticket/src/lib/admin-view-body/admin-view-body.component.html
  libs/admin-app/ticket/src/lib/admin-view-body/admin-view-body.component.ts
  libs/api/ticket/api/src/lib/controllers/api-ticket-api-controller.controller.ts
  libs/api/ticket/repository/src/lib/api-ticket-repository-data-access.ts
  libs/api/ticket/service/src/lib/api-ticket-service.module.ts
  libs/api/ticket/service/src/lib/api-ticket.service.ts
  libs/api/ticket/service/src/lib/queries/api-ticket-query.query.ts
  libs/api/ticket/service/src/lib/queries/api-ticket-quety-handler.handler.ts
Labels: scope:api, scope:repository, scope:ui, status:needs-tests, type:feature, scope:services, priority:high-med

#132 ✨ (api): Added services for Tech Team
  libs/api/profiles/tech-team/repository/src/index.ts
  libs/api/profiles/tech-team/service/src/lib/api-profiles-tech-team-service.module.ts
  libs/api/profiles/tech-team/service/src/lib/api-profiles-tech-team-service.service.spec.ts
  libs/api/profiles/tech-team/service/src/lib/api-profiles-tech-team-service.service.ts
  libs/api/profiles/tech-team/service/src/lib/commands/api-tech-team-command-handler.handler.ts
  libs/api/profiles/tech-team/service/src/lib/commands/api-tech-team-command.command.ts
  libs/api/profiles/tech-team/service/src/lib/dto/techTeam-dto.spec.ts
  libs/api/profiles/tech-team/service/src/lib/dto/techTeam.dto.ts
Labels: priority:high, status:needs-tests, scope:services

#141 🐛 (api): Fixed Dto issues, Linked tech team layers
  angular.json
  libs/admin-app/ticket/src/lib/admin-view-body/admin-view-body.component.ts
  libs/admin-app/ticket/src/lib/view-ticket-details/view-ticket-details.component.ts
  libs/api/profiles/tech-team/api/shared/techteamdto/.babelrc
  libs/api/profiles/tech-team/api/shared/techteamdto/.eslintrc.json
  libs/api/profiles/tech-team/api/shared/techteamdto/README.md
  libs/api/profiles/tech-team/api/shared/techteamdto/jest.config.ts
  libs/api/profiles/tech-team/api/shared/techteamdto/package.json
  libs/api/profiles/tech-team/api/shared/techteamdto/project.json
  libs/api/profiles/tech-team/api/shared/techteamdto/src/index.ts
  libs/api/profiles/tech-team/api/shared/techteamdto/src/lib/api-profiles-tech-team-api-shared-techteamdto.spec.ts
  libs/api/profiles/tech-team/api/shared/techteamdto/src/lib/api-profiles-tech-team-api-shared-techteamdto.ts
  libs/api/profiles/tech-team/api/shared/techteamdto/tsconfig.json
  libs/api/profiles/tech-team/api/shared/techteamdto/tsconfig.lib.json
  libs/api/profiles/tech-team/api/shared/techteamdto/tsconfig.spec.json
  libs/api/profiles/tech-team/api/src/lib/api-profiles-tech-team-api.module.ts
  libs/api/profiles/tech-team/api/src/lib/controllers/api-profiles-tech-team-api-controller.controller.spec.ts
  libs/api/profiles/tech-team/api/src/lib/controllers/api-profiles-tech-team-api-controller.controller.ts
  libs/api/profiles/tech-team/api/src/lib/dto/api-profiles-tech-team-api.dto.spec.ts
  libs/api/profiles/tech-team/service/src/index.ts
  libs/api/profiles/tech-team/service/src/lib/api-profiles-tech-team-service.service.spec.ts
  libs/api/profiles/tech-team/service/src/lib/dto/techTeam-dto.spec.ts
  libs/api/profiles/tech-team/service/src/lib/dto/techTeam.dto.ts
  libs/api/ticket/api/project.json
  libs/api/ticket/api/shared/ticketdto/.babelrc
  libs/api/ticket/api/shared/ticketdto/.eslintrc.json
  libs/api/ticket/api/shared/ticketdto/README.md
  libs/api/ticket/api/shared/ticketdto/jest.config.ts
  libs/api/ticket/api/shared/ticketdto/package.json
  libs/api/ticket/api/shared/ticketdto/project.json
  libs/api/ticket/api/shared/ticketdto/src/index.ts
  libs/api/ticket/api/shared/ticketdto/src/lib/api-ticket-api-shared-ticketdto.spec.ts
  libs/api/ticket/api/shared/ticketdto/src/lib/api-ticket-api-shared-ticketdto.ts
  libs/api/ticket/api/shared/ticketdto/tsconfig.json
  libs/api/ticket/api/shared/ticketdto/tsconfig.lib.json
  libs/api/ticket/api/shared/ticketdto/tsconfig.spec.json
  libs/api/ticket/api/src/lib/controllers/api-ticket-api-controller.controller.spec.ts
  libs/api/ticket/api/src/lib/controllers/api-ticket-api-controller.controller.ts
  libs/api/ticket/api/src/lib/dto/ticket-dto.spec.ts
  libs/api/ticket/api/src/lib/dto/ticket.dto.ts
  libs/api/ticket/repository/src/lib/api-ticket-repository-data-access.spec.ts
  libs/api/ticket/service/src/lib/api-ticket.service.spec.ts
  libs/api/ticket/service/src/lib/dto/ticket-dto.spec.ts
  libs/api/ticket/service/src/lib/dto/ticket.dto.ts
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.ts
  libs/public/ticket/src/lib/edit-ticket/edit-ticket.component.ts
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.ts
  libs/tech-team/ticket/src/lib/accepted-ticket-view/accepted-ticket-view.component.ts
  libs/tech-team/ticket/src/lib/edit-accepted-ticket/edit-accepted-ticket.component.ts
  libs/tech-team/ticket/src/lib/ticket-view-details/ticket-view-details.component.ts
  libs/tech-team/ticket/src/lib/ticket-view-page/ticket-view-page.component.ts
  package.json
  tsconfig.base.json
Labels: priority:high, scope:api, status:ready, type:change, type:refactor, scope:services
