Repository COS301-SE-2022/Grid-Watch, pull requests merged in 2022-06, with the labels that each got.

#142 ✅ (api): Added tests for Tech Team controllers
  libs/api/profiles/tech-team/api/src/lib/controllers/api-profiles-tech-team-api-controller.controller.spec.ts
Labels: priority:medium, scope:api, status:ready, type:test

#150 🔒️ (Security): Removed database url, added .env to gitignore
  .env
  .gitignore
Labels: priority:high, scope:db, status:ready, type:bug

#156 ✨ (UI) : Basic Google maps functionality
  .env
  .gitignore
  apps/admin/src/index.html
  apps/public/src/index.html
  apps/tech-team/src/index.html
  libs/api/profiles/tech-team/api/src/lib/controllers/api-profiles-tech-team-api-controller.controller.ts
  libs/api/profiles/tech-team/repository/src/lib/api-profiles-tech-team-repository-data-access.ts
  libs/public/home-page/src/lib/home-page-body/home-page-body.component.html
  libs/public/home-page/src/lib/home-page-body/home-page-body.component.scss
  libs/public/home-page/src/lib/home-page-body/home-page-body.component.ts
  libs/public/home-page/src/lib/public-home-page.module.ts
  libs/public/ticket/src/index.ts
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.html
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.spec.ts
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.ts
  libs/public/ticket/src/lib/edit-ticket/edit-ticket.component.html
  libs/public/ticket/src/lib/edit-ticket/edit-ticket.component.ts
  libs/public/ticket/src/lib/public-ticket.module.ts
  libs/public/ticket/src/lib/ticket-settings-options/ticket-settings-options.component.html
  libs/public/ticket/src/lib/ticket-settings-options/ticket-settings-options.component.scss
  libs/public/ticket/src/lib/ticket-settings-options/ticket-settings-options.component.spec.ts
  libs/public/ticket/src/lib/ticket-settings-options/ticket-settings-options.component.ts
  libs/tech-team/profile/src/lib/register-tech-team/register-tech-team.component.html
  libs/tech-team/profile/src/lib/register-tech-team/register-tech-team.component.ts
  package.json
  yarn.lock
Labels: scope:ui, status:not-ready, type:feature, priority:med-low

#157 ✨(api): Added CreatePicture endpoint
  .env
  .gitignore
  libs/api/ticket/api/src/lib/controllers/api-ticket-api-controller.controller.ts
  libs/api/ticket/service/src/lib/api-ticket-service.module.ts
  libs/api/ticket/service/src/lib/api-ticket.service.ts
  libs/api/ticket/service/src/lib/commands/api-ticket-command-handler.handler.ts
  libs/api/ticket/service/src/lib/commands/api-ticket-command.command.ts
Labels: priority:high, scope:api, status:ready, type:change

#159 ✨ (api): Added services for Picture upload
  libs/api/ticket/service/src/lib/api-ticket.service.ts
  libs/api/ticket/service/src/lib/commands/api-ticket-command-handler.handler.ts
  libs/api/ticket/service/src/lib/commands/api-ticket-command.command.ts
  libs/api/ticket/service/src/lib/queries/api-ticket-query.query.ts
  libs/api/ticket/service/src/lib/queries/api-ticket-quety-handler.handler.ts
  prisma/migrations/20220608103326_added_ticket_image/migration.sql
Labels: priority:high, scope:api, status:ready, scope:services

#163 🗃️ (db): Added crud operations for TechTeamTicket
  libs/api/profiles/tech-team/repository/src/lib/api-profiles-tech-team-repository-data-access.ts
Labels: priority:high, scope:db, status:ready, type:change

#167 🗃️ (db) : Updated schema and layers for techteam login + register
  libs/api/profiles/tech-team/api/src/lib/controllers/api-profiles-tech-team-api-controller.controller.ts
  libs/api/profiles/tech-team/repository/src/lib/api-profiles-tech-team-repository-data-access.spec.ts
  libs/api/profiles/tech-team/repository/src/lib/api-profiles-tech-team-repository-data-access.ts
  libs/api/profiles/tech-team/service/src/lib/api-profiles-tech-team-service.service.spec.ts
  libs/api/profiles/tech-team/service/src/lib/api-profiles-tech-team-service.service.ts
  libs/api/profiles/tech-team/service/src/lib/commands/api-tech-team-command-handler.handler.ts
  libs/api/profiles/tech-team/service/src/lib/commands/api-tech-team-command.command.ts
  libs/api/ticket/api/src/lib/controllers/api-ticket-api-controller.controller.spec.ts
  libs/api/ticket/api/src/lib/controllers/api-ticket-api-controller.controller.ts
  libs/api/ticket/repository/src/lib/api-ticket-repository-data-access.ts
  package.json
  prisma/migrations/20220608142227_updatedtechteam/migration.sql
  prisma/schema.prisma
  yarn.lock
Labels: scope:db, status:needs-info, type:feature, priority:high-med

#168 🗃️ (db) : Fix migration file
  prisma/migrations/20220608142227_updatedtechteam/migration.sql
  prisma/migrations/20220609082500_added_login/migration.sql
Labels: priority:medium

#169 🐛 (UI) : Small bug fixes
  libs/admin-app/ticket/src/lib/view-ticket-details/view-ticket-details.component.html
  libs/admin-app/ticket/src/lib/view-ticket-details/view-ticket-details.component.scss
  libs/admin-app/ticket/src/lib/view-ticket-details/view-ticket-details.component.ts
  libs/public/home-page/src/lib/home-page-body/home-page-body.component.ts
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.html
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.scss
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.spec.ts
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.ts
  libs/public/ticket/src/lib/edit-ticket/edit-ticket.component.html
  libs/public/ticket/src/lib/edit-ticket/edit-ticket.component.scss
  libs/public/ticket/src/lib/edit-ticket/edit-ticket.component.ts
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.html
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.scss
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.ts
  libs/shared-assets/src/lib/shared-images/location-pin-solid.svg
  libs/shared-assets/src/lib/shared-images/map-location-solid.svg
  libs/shared-ui/src/lib/nav-bar/nav-bar.component.html
  libs/shared-ui/src/lib/nav-bar/nav-bar.component.scss
  libs/shared-ui/src/lib/nav-bar/nav-bar.component.ts
  libs/tech-team/ticket/src/lib/edit-accepted-ticket/edit-accepted-ticket.component.html
  libs/tech-team/ticket/src/lib/edit-accepted-ticket/edit-accepted-ticket.component.scss
  libs/tech-team/ticket/src/lib/edit-accepted-ticket/edit-accepted-ticket.component.ts
  libs/tech-team/ticket/src/lib/tech-team-ticket.module.ts
  libs/tech-team/ticket/src/lib/ticket-view-details/ticket-view-details.component.html
  libs/tech-team/ticket/src/lib/ticket-view-details/ticket-view-details.component.scss
  libs/tech-team/ticket/src/lib/ticket-view-details/ticket-view-details.component.ts
Labels: priority:low

#171 💄 (UI): Changed colour for navbars
  .env
  libs/public/home-page/src/index.ts
  libs/public/home-page/src/lib/home-page-body/home-page-body.component.spec.ts
  libs/public/home-page/src/lib/home-page-body/home-page-body.component.ts
  libs/shared-ui/src/lib/nav-bar/nav-bar.component.html
  libs/shared-ui/src/lib/nav-bar/nav-bar.component.ts
Labels: priority:high, scope:ui, status:ready, type:cosmetic

#188 🗃️(db) : Restructered code and added subtasks model to schema
  cypress.config.ts
  libs/admin-app/dashboard/src/lib/dashboard-timeline/dashboard-timeline.component.html
  libs/admin-app/ticket/src/lib/admin-view-body/admin-view-body.component.ts
  libs/admin-app/ticket/src/lib/view-ticket-details/view-ticket-details.component.html
  libs/admin-app/ticket/src/lib/view-ticket-details/view-ticket-details.component.ts
  libs/api/profiles/tech-team/api/shared/techteamdto/src/lib/api-profiles-tech-team-api-shared-techteamdto.spec.ts
  libs/api/profiles/tech-team/api/shared/techteamdto/src/lib/api-profiles-tech-team-api-shared-techteamdto.ts
  libs/api/profiles/tech-team/api/src/lib/controllers/api-profiles-tech-team-api-controller.controller.spec.ts
  libs/api/profiles/tech-team/api/src/lib/controllers/api-profiles-tech-team-api-controller.controller.ts
  libs/api/profiles/tech-team/repository/src/lib/api-profiles-tech-team-repository-data-access.spec.ts
  libs/api/profiles/tech-team/repository/src/lib/api-profiles-tech-team-repository-data-access.ts
  libs/api/profiles/tech-team/service/src/lib/api-profiles-tech-team-service.module.ts
  libs/api/profiles/tech-team/service/src/lib/api-profiles-tech-team-service.service.spec.ts
  libs/api/profiles/tech-team/service/src/lib/api-profiles-tech-team-service.service.ts
  libs/api/profiles/tech-team/service/src/lib/commands/api-tech-team-command-handler.handler.ts
  libs/api/profiles/tech-team/service/src/lib/commands/api-tech-team-command.command.ts
  libs/api/ticket/api/shared/ticket-picture-dto/src/lib/api-ticket-api-shared-ticket-picture-dto.ts
  libs/api/ticket/api/shared/ticketdto/src/lib/api-ticket-api-shared-ticketdto.ts
  libs/api/ticket/api/src/lib/controllers/api-ticket-api-controller.controller.spec.ts
  libs/api/ticket/api/src/lib/controllers/api-ticket-api-controller.controller.ts
  libs/api/ticket/repository/src/lib/api-ticket-repository-data-access.spec.ts
  libs/api/ticket/repository/src/lib/api-ticket-repository-data-access.ts
  libs/api/ticket/service/src/lib/api-ticket-service.module.ts
  libs/api/ticket/service/src/lib/api-ticket.service.spec.ts
  libs/api/ticket/service/src/lib/api-ticket.service.ts
  libs/api/ticket/service/src/lib/commands/api-ticket-command-handler.handler.ts
  libs/api/ticket/service/src/lib/commands/api-ticket-command.command.ts
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.html
  libs/public/ticket/src/lib/create-ticket/create-ticket.component.ts
  libs/public/ticket/src/lib/edit-ticket/edit-ticket.component.html
  libs/public/ticket/src/lib/edit-ticket/edit-ticket.component.ts
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.html
  libs/public/ticket/src/lib/ticket-body/ticket-body.component.ts
  libs/shared-ui/src/lib/services/Ticket/ticket.service.ts
  libs/tech-team/profile/src/lib/register-tech-team/register-tech-team.component.html
  libs/tech-team/profile/src/lib/register-tech-team/register-tech-team.component.ts
  libs/tech-team/ticket/src/lib/accepted-ticket-view/accepted-ticket-view.component.html
  libs/tech-team/ticket/src/lib/edit-accepted-ticket/edit-accepted-ticket.component.html
  libs/tech-team/ticket/src/lib/edit-accepted-ticket/edit-accepted-ticket.component.ts
  libs/tech-team/ticket/src/lib/ticket-view-details/ticket-view-details.component.html
  libs/tech-team/ticket/src/lib/ticket-view-details/ticket-view-details.component.ts
  libs/tech-team/ticket/src/lib/ticket-view-page/ticket-view-page.component.html
  libs/tech-team/ticket/src/lib/ticket-view-page/ticket-view-page.component.ts
  prisma/migrations/20220609121757_standardized_fieldnames/migration.sql
  prisma/migrations/20220625192800_techteamticketfix/migration.sql
  prisma/migrations/20220626062155_added_subtasks/migration.sql
  prisma/migrations/20220626072349_addedsubtasks/migration.sql
  prisma/migrations/20220626083341_updated_subtasks/migration.sql
  prisma/migrations/20220626083436_subtasktypofix/migration.sql
  prisma/schema.prisma
Labels: scope:db, status:needs-info, type:feature, type:fix, priority:high-med
